### PR TITLE
Fetch data in Action and CP updates

### LINKED ISSUE #1: Add fetch now widget/button

### LINKED ISSUE #3: Store fetch time
At the moment the json file in storage is 'just' the json response stored. 
But it might be better to als store the time of api-fetch in there:

```json
{
  "fetched_at": "2021-02-25 14:00:23",
  "response": --- response here ---
}
```

### PR DESCRIPTION
**Pull request by vannut**
This PR adds some logic to the CP to display and fetch the weather data from the API. 

To prevent duplication I extracted the fetch into its own Action. Which is used in the Artisan Command as well in the CpController. 

In the whole rewrite I also added a fetched_at value to the stored json. Closes #3 
Also Closes #1

### CODE REVIEW

**Comment by vannut** [comment]
In the whole rewrite I also added a fetched_at value to the stored json. Closes #3

**Comment by vannut** [comment]
@Wibbmer would you be so kind to test this PR?

**Comment by Wibbmer** [comment]
New CP looks nice, seems to me it's all working as it should. Fetching and updating via CP as well as via the artisan command.

I could see it to be handy to make the time of the fetch available to the tag as well though, in case you would like to display how up to date the forecast is.

**Comment by vannut** [comment]
That's a good one. Let me see if I can find some time to inject it in the tag later this weekend.

**Pull request merged**
